variables:
  AUDIT_AWS_S3_SEND_ON:
      description: "Send reports always or only when there is a change? Options - always / change. Default is change."
      required: true
      type: string
      default: "changelalalaasasasasasasl"
  AUDIT_AWS_S3_ALLOW_EMPTY:
      description: "Would you like to receive empty reports? Options - true / false. Default is false."
      required: true
      type: string
      default: false

  AUDIT_AWS_S3_ALLOW_EMPTY_Nesadasdw:
      description: "Would you like to receive empty reports? Options - true / false. Default is false."
      required: true
      type: number
      default:

  AUDIT_AWS_S3_ALLOW_EMPTYsadad_2gsdfg:
      description: "Would you like to receive empty reports? Options - true / false. Default is false."
      required: false
      type: string
      default: