variables:
  AUDIT_AWS_S3_ALLOW_EMPTY:
      description: "Would you like to receive empty reports? Options - true / false. Default is false."
      required: false
      type: string
      default: false

  AUDIT_AWS_S3_ALLOW_EMPTY_New:
      description: "Would you like to receive empty reports? Options - true / false. Default is false."
      required: true
      type: string
      default:
