variables:
  TEST_NEW:
      description: "test new var added"
      required: true
      type: string
      default: "change"
  TEST_DEFAULT:
      description: "test default value"
      required: false
      type: string
      default: wersw
  TEST_TYPE:
      description: "test type change"
      required: false
      type: number
      default: 4
  TEST_REQUIRED:
      description: "test required field"
      required: false
      type: number
      default: 4