variables:
  TEST_NEW:
      description: "test"
      required: true
      type: string
      default: "change"
  TEST_DEFAULT:
      description: "test"
      required: false
      type: string
      default: qsfsd
  TEST_TYPE:
      description: "test"
      required: false
      type: string
      default: 4
  TEST_REQUIRED:
      description: "test"
      required: true
      type: number
      default: 4
  TEST_REMOVED:
      description: "test"
      required: false
      type: number
      default: 4